version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: rate_limiter_postgres
    restart: always
    environment:
      POSTGRES_DB: rate_limiter_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rate_limiter_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: rate_limiter_app
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: rate_limiter_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - rate_limiter_net

volumes:
  postgres_data:

networks:
  rate_limiter_net:
    driver: bridge
